spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
  datasource:
    url: jdbc:postgresql://localhost:5432/AudioParser

